### ISSUE TITLE
Github actions do not run properly

### ISSUE THREAD

**Issue by ggsdc** [baobabsoluciones/corn#81]
Without any change that I can see all github worflows seem to be failing on both open PR. The error is always the same:

```
Run python -m unittest discover -s cornflow.tests.ldap
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/main.py", line 271, in runTests
    self.result = testRunner.run(self.test)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_testing/utils.py", line 131, in __call__
    self._pre_setup()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_testing/utils.py", line 144, in _pre_setup
    self.app = self.create_app()
  File "/home/runner/work/corn/corn/cornflow/tests/custom_test_case.py", line 456, in create_app
    app = create_app("testing")
  File "/home/runner/work/corn/corn/cornflow/app.py", line 54, in create_app
    docs.register(target=res["resource"], endpoint=res["endpoint"])
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/extension.py", line 125, in register
    resource_class_args, resource_class_kwargs)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/extension.py", line 72, in _defer
    bound()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/extension.py", line 147, in _register
    resource_class_kwargs=resource_class_kwargs,
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 39, in convert
    return [self.get_path(rule, target, **kwargs) for rule in rules]
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 39, in <listcomp>
    return [self.get_path(rule, target, **kwargs) for rule in rules]
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 53, in get_path
    for method, view in operations.items()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 54, in <dictcomp>
    if method.lower() in (set(valid_methods) - excluded_methods)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 66, in get_operation
    'parameters': self.get_parameters(rule, view, docs, parent),
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/flask_apispec/apidoc.py", line 92, in get_parameters
    extra_params += openapi_converter(schema, **options) if args else []
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 135, in schema2parameters
    for field_name, field_obj in fields.items()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 135, in <listcomp>
    for field_name, field_obj in fields.items()
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/apispec/ext/marshmallow/openapi.py", line 151, in _field2parameter
    prop = self.field2property(field)
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/apispec/ext/marshmallow/field_converter.py", line 172, in field2property
    ret.update(attr_func(field, ret=ret))
  File "/opt/hostedtoolcache/Python/3.7.11/x64/lib/python3.7/site-packages/apispec/ext/marshmallow/field_converter.py", line 219, in field2default
    default = field.load_default
AttributeError: 'Integer' object has no attribute 'load_default'
Error: Process completed with exit code 1.
```

**Comment by ggsdc** [comment]
This issue should be solved now with the update to requirements on PR #78. The origin of the error came from not having an `apispec `dependency on requirements, as it was installing its latest version (5.1.0 or 5.0.0) that drops support of marshmallow older versions, prior to 3.13.0, and we were using 3.6.0 as enforced by our requirements.

One of the main changes is that now `marshmallow `does not accept the `default `option on the schemas, but it has a `load_default` and `dump_default` option.

I'm going to open a new issue to review the changes needed to bump from marshmallow 3.6.0 to newer versions and update other libraries as well if the changes introduced in newer `marshmallow ` seem useful.
